# -*- coding: utf-8 -*-
"""charging-data-cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFtomnR21bGq-FN2dP79hFj3E8-snxy-
"""

import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

# Read dataset
stations_raw = pd.read_csv("alt_fuel_stations (Feb 17 2026).csv")

print(stations_raw.shape)
stations_raw.head()

stations = stations_raw.copy()

# Keep only Maryland electric charging stations
stations = stations[
    (stations["State"].astype(str).str.upper().str.strip() == "MD") &
    (stations["Fuel Type Code"].astype(str).str.upper().str.strip() == "ELEC")
].copy()

# Keep only active stations
stations["Status Code"] = stations["Status Code"].astype(str).str.upper().str.strip()
stations = stations[stations["Status Code"] == "E"].copy()

print("Rows after filtering:", stations.shape[0])

# Drop rows missing coordinates
stations = stations.dropna(subset=["Latitude", "Longitude"]).copy()

print("Rows with coordinates:", stations.shape[0])

# Create GeoDataFrame of station points
geometry = [Point(xy) for xy in zip(stations["Longitude"], stations["Latitude"])]
stations_gdf = gpd.GeoDataFrame(stations, geometry=geometry, crs="EPSG:4326")

stations_gdf.head()

# Read Maryland county boundaries directly from Census TIGER shapefile
counties_url = "https://www2.census.gov/geo/tiger/TIGER2025/COUNTY/tl_2025_us_county.zip"
counties = gpd.read_file(counties_url)

# Keep only Maryland counties (state FIPS = 24)
md_counties = counties[counties["STATEFP"] == "24"].copy()

# Keep useful columns
md_counties = md_counties[["NAME", "geometry"]].copy()

md_counties.head()

# Spatial join: assign each station to a county
stations_with_county = gpd.sjoin(
    stations_gdf,
    md_counties,
    how="left",
    predicate="within"
)

# Clean county names
stations_with_county["County"] = stations_with_county["NAME"].replace({
    "Baltimore": "Baltimore County"
})

stations_with_county["County"].value_counts(dropna=False).head(30)

# Drop rows where county was not found
stations_with_county = stations_with_county.dropna(subset=["County"]).copy()

print("Rows after county assignment:", stations_with_county.shape[0])
print("Unique counties:", stations_with_county["County"].nunique())
print(sorted(stations_with_county["County"].unique()))

# Create modeling variables
stations_with_county["Station_Count"] = 1

stations_with_county["Total_Charging_Ports"] = (
    stations_with_county["EV Level1 EVSE Num"] +
    stations_with_county["EV Level2 EVSE Num"] +
    stations_with_county["EV DC Fast Count"]
)

stations_with_county["Has_Level2"] = (stations_with_county["EV Level2 EVSE Num"] > 0).astype(int)
stations_with_county["Has_DC_Fast"] = (stations_with_county["EV DC Fast Count"] > 0).astype(int)

stations_with_county["Public_Access"] = (
    stations_with_county["Access Code"]
    .astype(str)
    .str.lower()
    .eq("public")
    .astype(int)
)

# County-level aggregation for modeling
stations_county = (
    stations_with_county.groupby("County", as_index=False)
    .agg(
        Charging_Stations=("Station_Count", "sum"),
        Level1_Ports=("EV Level1 EVSE Num", "sum"),
        Level2_Ports=("EV Level2 EVSE Num", "sum"),
        DC_Fast_Ports=("EV DC Fast Count", "sum"),
        Total_Charging_Ports=("Total_Charging_Ports", "sum"),
        Public_Stations=("Public_Access", "sum"),
        Stations_With_Level2=("Has_Level2", "sum"),
        Stations_With_DC_Fast=("Has_DC_Fast", "sum")
    )
    .sort_values("Charging_Stations", ascending=False)
    .reset_index(drop=True)
)

stations_county.head(15)

stations_county.to_csv("charging_cleaned.csv", index=False)
stations_with_county.to_csv("charging_cleaned_station_level.csv", index=False)