# -*- coding: utf-8 -*-
"""ev-data-cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gMsQSw6AaGD5DL36TcLN6ulU1rWgOdP
"""

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

# Upload/read your EV dataset manually in Colab
ev_raw = pd.read_csv("MDOT_MVA_Electric_and_Plug-in_Hybrid_Vehicle_Registrations_by_County_as_of_each_month_end_20260407.csv")

print(ev_raw.shape)
ev_raw.head()

ev_raw.info()

ev = ev_raw.copy()

# Clean key columns
ev["Year_Month"] = pd.to_datetime(ev["Year_Month"], errors="coerce")

ev["County"] = (
    ev["County"]
    .astype(str)
    .str.strip()
    .str.upper()
)

ev["Fuel_Category"] = (
    ev["Fuel_Category"]
    .astype(str)
    .str.strip()
    .str.replace("Plug-In Hybrid", "Plug-in Hybrid", regex=False)
)

ev["Count"] = (
    ev["Count"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)
ev["Count"] = pd.to_numeric(ev["Count"], errors="coerce")

# Keep only Maryland counties and standardize names
county_map = {
    "ALLEGANY": "Allegany",
    "ANNE ARUNDEL": "Anne Arundel",
    "BALTIMORE": "Baltimore County",
    "BALTIMORE CITY": "Baltimore City",
    "CALVERT": "Calvert",
    "CAROLINE": "Caroline",
    "CARROLL": "Carroll",
    "CECIL": "Cecil",
    "CHARLES": "Charles",
    "DORCHESTER": "Dorchester",
    "FREDERICK": "Frederick",
    "GARRETT": "Garrett",
    "HARFORD": "Harford",
    "HOWARD": "Howard",
    "KENT": "Kent",
    "MONTGOMERY": "Montgomery",
    "PRINCE GEORGES": "Prince George's",
    "PRINCE GEORGE'S": "Prince George's",
    "QUEEN ANNES": "Queen Anne's",
    "QUEEN ANNE'S": "Queen Anne's",
    "SAINT MARYS": "St. Mary's",
    "ST. MARYS": "St. Mary's",
    "ST. MARY'S": "St. Mary's",
    "SOMERSET": "Somerset",
    "TALBOT": "Talbot",
    "WASHINGTON": "Washington",
    "WICOMICO": "Wicomico",
    "WORCESTER": "Worcester"
}

ev = ev[ev["County"].isin(county_map.keys())].copy()
ev["County"] = ev["County"].map(county_map)

print(ev["County"].nunique())
print(sorted(ev["County"].unique()))

# Remove missing values in important columns
ev = ev.dropna(subset=["Year_Month", "County", "Fuel_Category", "Count"]).copy()

ev = ev[ev["Fuel_Category"] == "Electric"]

# Group by month, county, fuel category
ev_monthly = (
    ev.groupby(["Year_Month", "County", "Fuel_Category"], as_index=False)["Count"]
      .sum()
)

ev_monthly.head()

# Pivot fuel categories into columns
ev_cleaned = (
    ev_monthly
    .pivot(index=["Year_Month", "County"], columns="Fuel_Category", values="Count")
    .reset_index()
    .fillna(0)
)

# Make sure both columns exist
for col in ["Electric", "Plug-in Hybrid"]:
    if col not in ev_cleaned.columns:
        ev_cleaned[col] = 0

ev_cleaned["Electric"] = ev_cleaned["Electric"].astype(int)
ev_cleaned["Plug-in Hybrid"] = ev_cleaned["Plug-in Hybrid"].astype(int)

# Total EV count
ev_cleaned["EV_Total"] = ev_cleaned["Electric"] + ev_cleaned["Plug-in Hybrid"]

ev_cleaned = ev_cleaned.sort_values(["Year_Month", "County"]).reset_index(drop=True)

ev_cleaned.head()

# Latest county snapshot for later merge/modeling
latest_month = ev_cleaned["Year_Month"].max()

ev_latest = ev_cleaned[ev_cleaned["Year_Month"] == latest_month].copy()

print("Latest month:", latest_month)
print(ev_latest.shape)
ev_latest.head()

# Optional: check top counties by EV total
ev_latest.sort_values("EV_Total", ascending=False).head(10)

# Save files
ev_latest.to_csv("ev_cleaned.csv", index=False)

"""##Uploading Cleaned Charging Station Dataset

"""

import pandas as pd

# Read the cleaned charging station dataset
charging = pd.read_csv("charging_cleaned.csv")

print(charging.shape)
charging.head()

# Make sure county names are clean in both datasets
ev_latest["County"] = ev_latest["County"].astype(str).str.strip()
charging["County"] = charging["County"].astype(str).str.strip()

# Merge EV dataset with cleaned charging dataset
merged_df = ev_latest.merge(charging, on="County", how="inner")

print(merged_df.shape)
merged_df.head()

# Create EV-to-station ratio
merged_df["EV_per_Station"] = merged_df["EV_Total"] / merged_df["Charging_Stations"]

# Optional: avoid division issues if a county somehow has 0 charging stations
merged_df["EV_per_Station"] = merged_df["EV_per_Station"].replace([float("inf"), -float("inf")], pd.NA)

# Quick check
merged_df[[
    "County",
    "EV_Total",
    "Charging_Stations",
    "Level2_Ports",
    "DC_Fast_Ports",
    "EV_per_Station"
]].head(10)

# Save final merged dataset
merged_df.to_csv("final_dataset.csv", index=False)

print("Saved: final_dataset.csv")