# -*- coding: utf-8 -*-
"""DATA205 Visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRXaGHnLZSeO-kI1nRaP3vsgcB2HSEMQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.patches as mpatches
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Colors for grapgs
NAVY  = '#0A2342'
TEAL  = '#028090'
CORAL = '#E05252'
SLATE = '#4A5568'
LGRAY = '#F4F7FA'
GRP_COLORS = [CORAL, '#F5A623', TEAL, NAVY]

# add sources text under graphs
def add_source(fig, text):
    fig.text(
        0.01, -0.02, text,
        fontsize=8.5, color='#888888', fontstyle='italic',
        ha='left', va='top', transform=fig.transFigure
    )

def style_ax(ax):
    ax.set_facecolor('#FFFFFF')
    ax.grid(True, axis='y', alpha=0.3, color='#D1DDE6')
    for sp in ax.spines.values():
        sp.set_edgecolor('#D1DDE6')
    ax.tick_params(colors=SLATE)

#loading data
df      = pd.read_csv("final_dataset.csv")
ev_time = pd.read_csv("ev_county_monthly_cleaned.csv")
inc_raw = pd.read_csv("maryland_income_by_county.csv")

ev_time["Year_Month"] = pd.to_datetime(ev_time["Year_Month"])

# clean and merge
inc = inc_raw[~inc_raw['County'].isin([
    'United States', 'Maryland', 'Baltimore City'   # <-- key fix
])].copy()

inc['County'] = inc['County'].str.replace(' County', '').str.strip()

name_map = {
    'Allegany': 'Allegany', 'Anne Arundel': 'Anne Arundel',
    'Baltimore': 'Baltimore County', 'Calvert': 'Calvert',
    'Caroline': 'Caroline', 'Carroll': 'Carroll', 'Cecil': 'Cecil',
    'Charles': 'Charles', 'Dorchester': 'Dorchester', 'Frederick': 'Frederick',
    'Garrett': 'Garrett', 'Harford': 'Harford', 'Howard': 'Howard',
    'Kent': 'Kent', 'Montgomery': 'Montgomery',
    'Prince Georges': "Prince George's", 'Queen Annes': "Queen Anne's",
    'Somerset': 'Somerset', 'St. Marys': "St. Mary's", 'Talbot': 'Talbot',
    'Washington': 'Washington', 'Wicomico': 'Wicomico', 'Worcester': 'Worcester',
}
inc['County'] = inc['County'].map(name_map)
inc = inc.dropna(subset=['County'])
inc = inc.rename(columns={'Value (Dollars)': 'Median_Income'})[['County', 'Median_Income']]

merged = df.merge(inc, on='County', how='inner')
merged['Income_Group'] = pd.qcut(merged['Median_Income'], 4,
    labels=['Low\n(<$75K)', 'Lower-Mid\n($75-110K)', 'Upper-Mid\n($110-125K)', 'High\n(>$125K)'])
merged['Income_Label'] = pd.qcut(merged['Median_Income'], 4,
    labels=['Low', 'Lower-Mid', 'Upper-Mid', 'High'])

print(f"Dataset ready: {merged.shape[0]} counties")
print(merged['County'].sort_values().tolist())

# EV Growth Over time

monthly_total = ev_time.groupby("Year_Month", as_index=False)["EV_Total"].sum()
top3_counties = df.nlargest(3, 'EV_Total')['County'].tolist()
top3_monthly  = (ev_time[ev_time['County'].isin(top3_counties)]
                 .groupby(['Year_Month', 'County'], as_index=False)['EV_Total'].sum())

fig, ax = plt.subplots(figsize=(12, 6))
fig.patch.set_facecolor(LGRAY)
ax.set_facecolor('#FFFFFF')

ax.fill_between(monthly_total['Year_Month'], monthly_total['EV_Total'],
                alpha=0.12, color=TEAL)
ax.plot(monthly_total['Year_Month'], monthly_total['EV_Total'],
        color=TEAL, lw=3, label='Maryland Statewide', zorder=5)

county_colors = [NAVY, CORAL, '#F5A623']
for county, color in zip(top3_counties, county_colors):
    d = top3_monthly[top3_monthly['County'] == county].sort_values('Year_Month')
    ax.plot(d['Year_Month'], d['EV_Total'],
            lw=2, linestyle='--', color=color, label=county, alpha=0.85)

last = monthly_total.iloc[-1]
ax.annotate(f"  {last['EV_Total']:,} total",
            xy=(last['Year_Month'], last['EV_Total']),
            fontsize=10, fontweight='bold', color=TEAL, va='center')

ax.set_title("EV Growth Over Time Maryland Counties",
             fontsize=13, fontweight='bold', color=NAVY, pad=14)
ax.set_xlabel('Date', fontsize=11, color=SLATE)
ax.set_ylabel('EV Registrations', fontsize=11, color=SLATE)
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))
ax.legend(fontsize=10, framealpha=0.9)
ax.grid(True, alpha=0.3, color='#D1DDE6')
for sp in ax.spines.values():
    sp.set_edgecolor('#D1DDE6')

ax.text(0.02, 0.97,
    '~88% statewide growth in 2 years\nTop 3 counties have more than others combined',
    transform=ax.transAxes, fontsize=10, color=NAVY, va='top',
    bbox=dict(boxstyle='round,pad=0.5', facecolor='#E8F4F8', edgecolor=TEAL))

add_source(fig,
    "Data: Maryland Motor Vehicle Administration (MVA) Monthly EV Registrations by County  |  "
    "Source: data.gov / Maryland Open Data Portal (opendata.maryland.gov)")

plt.tight_layout()
plt.savefig('viz1_ev_growth_over_time.png', dpi=150, bbox_inches='tight')
plt.show()

# EVs vs Charging Stations (dual axis bar)

top10 = merged.nlargest(10, 'EV_Total').sort_values('EV_Total', ascending=False).reset_index(drop=True)
x     = np.arange(len(top10))
width = 0.38

fig, ax1 = plt.subplots(figsize=(13, 6))
fig.patch.set_facecolor(LGRAY)
ax1.set_facecolor('#FFFFFF')

ax1.bar(x - width/2, top10['EV_Total'], width,
        color=NAVY, label='EV Registrations', edgecolor='white', linewidth=0.8)
ax1.set_ylabel('EV Registrations', fontsize=11, color=NAVY)
ax1.tick_params(axis='y', labelcolor=NAVY)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f'{v:,.0f}'))

ax2 = ax1.twinx()
ax2.bar(x + width/2, top10['Charging_Stations'], width,
        color=TEAL, label='Charging Stations', edgecolor='white', linewidth=0.8)
ax2.set_ylabel('Charging Stations', fontsize=11, color=TEAL)
ax2.tick_params(axis='y', labelcolor=TEAL)

for i, (_, row) in enumerate(top10.iterrows()):
    ax1.text(i, row['EV_Total'] + 500, f"{row['EV_per_Station']:.0f}:1",
             ha='center', fontsize=9, fontweight='bold', color=CORAL)

ax1.set_xticks(x)
ax1.set_xticklabels(top10['County'], rotation=35, ha='right', fontsize=10)
ax1.set_title("EV's are Outpacing Chargers in High Income Counties\n"
              "(Red number = EVs per charging station: state avg is 42)",
              fontsize=12, fontweight='bold', color=NAVY, pad=12)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, fontsize=11, framealpha=0.9, loc='upper right')
ax1.grid(True, axis='y', alpha=0.3, color='#D1DDE6')
for sp in ax1.spines.values():
    sp.set_edgecolor('#D1DDE6')

add_source(fig,
    "Data: Maryland MVA EV Registrations (data.gov / opendata.maryland.gov)  |  "
    "U.S. Dept. of Energy / AFDC Charging Station Locations (afdc.energy.gov)")

plt.tight_layout()
plt.savefig('viz2_ev_vs_chargers.png', dpi=150, bbox_inches='tight')
plt.show()


#Income vs EV Adoption (scatter)

color_map = dict(zip(['Low', 'Lower-Mid', 'Upper-Mid', 'High'], GRP_COLORS))

fig, ax = plt.subplots(figsize=(11, 7))
fig.patch.set_facecolor(LGRAY)
ax.set_facecolor('#FFFFFF')

for _, row in merged.iterrows():
    ax.scatter(row['Median_Income'], row['EV_Total'],
               color=color_map[row['Income_Label']],
               s=130, zorder=5, edgecolors='white', linewidths=1.2)

label_offsets = {
    'Montgomery':      (2000, -2200),
    'Howard':          (-30000, 600),
    "Prince George's": (2000, 400),
    'Anne Arundel':    (2000, 300),
    'Frederick':       (2000, 300),
    'Carroll':         (2000, 300),
    'Garrett':         (1500, 300),
    'Somerset':        (1500, 300),
}
for _, row in merged.iterrows():
    if row['County'] in label_offsets:
        dx, dy = label_offsets[row['County']]
        ax.text(row['Median_Income'] + dx, row['EV_Total'] + dy,
                row['County'], fontsize=8.5, color=SLATE)

m, b, r, *_ = stats.linregress(merged['Median_Income'], merged['EV_Total'])
x_l = np.linspace(merged['Median_Income'].min(), merged['Median_Income'].max(), 200)
ax.plot(x_l, m * x_l + b, color='#888', lw=2, linestyle='--', alpha=0.7)

patches = [mpatches.Patch(color=c, label=l) for c, l in zip(GRP_COLORS,
    ['Low (<$75K)', 'Lower-Mid ($75-110K)', 'Upper-Mid ($110-125K)', 'High (>$125K)'])]
patches.append(plt.Line2D([0], [0], color='#888', linestyle='--', label=f'Trend (r = {r:.2f})'))
ax.legend(handles=patches, fontsize=10, framealpha=0.9, loc='lower right')


ax.set_xlabel('Median Household Income ($)', fontsize=12, color=SLATE)
ax.set_ylabel('EV Registrations', fontsize=12, color=SLATE)
ax.set_title('Income Is a Major Driver of Where EVs Show Up',
             fontsize=13, fontweight='bold', color=NAVY, pad=14)
ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}K'))
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))
ax.grid(True, alpha=0.3, color='#D1DDE6')
for sp in ax.spines.values():
    sp.set_edgecolor('#D1DDE6')

add_source(fig,
    "Data: Maryland MVA EV Registrations (data.gov / opendata.maryland.gov)  |  "
    "Median Household Income: Montgomery County Open Data & U.S. Census ACS 5-Year Estimates (data.census.gov)")

plt.tight_layout()
plt.savefig('viz3_income_vs_ev.png', dpi=150, bbox_inches='tight')
plt.show()

# The Income Paradox (side-by-side bars)

group_stats = merged.groupby('Income_Group', observed=True)[
    ['EV_Total', 'EV_per_Station']].mean().reset_index()

fig, axes = plt.subplots(1, 2, figsize=(13, 6))
fig.patch.set_facecolor(LGRAY)
fig.suptitle("Wealth Increases EV Adoption but Also Worsens the Infrastructure Gap",
             fontsize=13, fontweight='bold', color=NAVY, y=1.02)

for ax, col, title, ylabel, show_avg in zip(
    axes,
    ['EV_Total', 'EV_per_Station'],
    ['Higher Income = Dramatically More EVs',
     'But Richer Counties Have a Worse Charger Shortage'],
    ['Avg EV Registrations', 'Avg EVs per Charging Station'],
    [False, True]
):
    style_ax(ax)
    bars = ax.bar(group_stats['Income_Group'], group_stats[col],
                  color=GRP_COLORS, edgecolor='white', linewidth=1.2, width=0.55)
    ax.set_title(title, fontsize=12, fontweight='bold', color=NAVY, pad=10)
    ax.set_xlabel('Income Group', fontsize=11, color=SLATE)
    ax.set_ylabel(ylabel, fontsize=11, color=SLATE)
    ax.set_ylim(0, group_stats[col].max() * 1.22)
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

    for bar, val in zip(bars, group_stats[col]):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + group_stats[col].max() * 0.03,
                f'{val:,.1f}', ha='center', fontsize=11,
                fontweight='bold', color=NAVY)

    if show_avg:
        ax.axhline(42.5, color=CORAL, linestyle='--', lw=2, label='State avg: 42.5')
        ax.legend(fontsize=10)

add_source(fig,
    "Data: Maryland MVA EV Registrations (data.gov / opendata.maryland.gov)  |  "
    "U.S. Dept. of Energy / AFDC Charging Stations (afdc.energy.gov)  |  "
    "Income: Montgomery County Open Data & U.S. Census ACS (data.census.gov)")

plt.tight_layout()
plt.savefig('viz4_income_paradox.png', dpi=150, bbox_inches='tight')
plt.show()

#Charger Type Mix (stacked horizontal bar)

df_top = merged.nlargest(12, 'EV_Total').sort_values('EV_Total').copy()
df_top['pct_l2'] = df_top['Stations_With_Level2'] / df_top['Charging_Stations'] * 100
df_top['pct_dc'] = df_top['Stations_With_DC_Fast'] / df_top['Charging_Stations'] * 100

fig, ax = plt.subplots(figsize=(13, 7))
fig.patch.set_facecolor(LGRAY)
ax.set_facecolor('#FFFFFF')

y = np.arange(len(df_top))
ax.barh(y, df_top['pct_l2'], color=TEAL,
        label='Level 2 Stations (%)', height=0.6)
ax.barh(y, df_top['pct_dc'], left=df_top['pct_l2'], color=CORAL,
        label='DC Fast Stations (%)', height=0.6, alpha=0.88)

ax.set_yticks(y)
ax.set_yticklabels(df_top['County'], fontsize=11, color=SLATE)
ax.set_xlabel('% Share of Charging Stations by Type', fontsize=11, color=SLATE)
ax.set_title("Charger Type Distribution by Counties\n"
             "(Top 12 counties by EV registrations)",
             fontsize=12, fontweight='bold', color=NAVY, pad=12)

for i, (_, row) in enumerate(df_top.iterrows()):
    ax.text(102, i,
            f"{row['EV_Total']:,} EVs  |  {row['EV_per_Station']:.0f}/station",
            va='center', fontsize=8.5, color=NAVY)

ax.set_xlim(0, 128)
ax.axvline(80, color='#888', linestyle=':', lw=1.2, alpha=0.6)
ax.text(80.5, -0.7, '80% Level 2', fontsize=8, color='#888')
ax.legend(fontsize=11, loc='lower right')
ax.grid(True, axis='x', alpha=0.3, color='#D1DDE6')
for sp in ax.spines.values():
    sp.set_edgecolor('#D1DDE6')


add_source(fig,
    "Data: U.S. Dept. of Energy / Alternative Fuels Data Center (AFDC) Charging Station Inventory (afdc.energy.gov)  |  "
    "EV Registrations: Maryland MVA via data.gov / opendata.maryland.gov")

plt.tight_layout()
plt.savefig('viz5_charger_type_mix.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nWhat I Learned:")
print("  1. EV's are increasing fast and concentrated")
print("  2. Every top county is falling behind in charging stations")
print("  3. Low income counties have less registered EV's")
print("  4. Richer counties have more EVs but worse infrastructure gaps")
print("  5. Level 2 chargers serves residents, DC Fast chargers serves highways")