# -*- coding: utf-8 -*-
"""eda-visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRXaGHnLZSeO-kI1nRaP3vsgcB2HSEMQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import seaborn as sns

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

df = pd.read_csv("final_dataset.csv")
ev_time = pd.read_csv("ev_county_monthly_cleaned.csv")

print(df.shape)
print(ev_time.shape)

df.head()

ev_time.head()

ev_time["Year_Month"] = pd.to_datetime(ev_time["Year_Month"])

"""##Visualization 1 Top Counties by EV Count"""

top_ev = df.sort_values("EV_Total", ascending=False).head(10)

plt.figure(figsize=(12, 6))
plt.bar(top_ev["County"], top_ev["EV_Total"])
plt.xticks(rotation=45, ha="right")
plt.title("Top Maryland Counties by EV Adoption")
plt.xlabel("County")
plt.ylabel("EV Count")
plt.tight_layout()
plt.savefig("top_counties_ev_adoption.png", bbox_inches="tight")
plt.show()

"""##Visualization 2 Top Counties by Charger Count"""

top_chargers = df.sort_values("Charging_Stations", ascending=False).head(10)

plt.figure(figsize=(12, 6))
plt.bar(top_chargers["County"], top_chargers["Charging_Stations"])
plt.xticks(rotation=45, ha="right")
plt.title("Top Maryland Counties by Charging Stations")
plt.xlabel("County")
plt.ylabel("Charging Stations")
plt.tight_layout()
plt.savefig("top_counties_charging_stations.png", bbox_inches="tight")
plt.show()

"""##Visualization 3 EV Growth Over Time"""

monthly_total = ev_time.groupby("Year_Month", as_index=False)["EV_Total"].sum()

plt.figure(figsize=(12, 6))
plt.plot(monthly_total["Year_Month"], monthly_total["EV_Total"])
plt.title("EV Growth Over Time in Maryland")
plt.xlabel("Date")
plt.ylabel("EV Count")
plt.tight_layout()
plt.savefig("ev_growth_over_time.png", bbox_inches="tight")
plt.show()

"""##Visualization 4 EV vs Charging Stations"""

plt.figure(figsize=(10, 6))
plt.scatter(df["Charging_Stations"], df["EV_Total"])
plt.title("EV Count vs Charging Stations by County")
plt.xlabel("Charging Stations")
plt.ylabel("EV Count")
plt.tight_layout()
plt.savefig("ev_vs_charging_stations_scatter.png", bbox_inches="tight")
plt.show()

"""##Visualization 5 Correlation Heatmap"""

corr_cols = ["EV_Total", "Charging_Stations", "Level2_Ports", "DC_Fast_Ports", "EV_per_Station"]
corr_matrix = df[corr_cols].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap="Blues")
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("correlation_heatmap.png", bbox_inches="tight")
plt.show()

"""##Visualization 6 EV per Station Ratio"""

top_ratio = df.sort_values("EV_per_Station", ascending=False).head(10)

plt.figure(figsize=(12, 6))
plt.bar(top_ratio["County"], top_ratio["EV_per_Station"])
plt.xticks(rotation=45, ha="right")
plt.title("Top Counties by EV-to-Charging-Station Ratio")
plt.xlabel("County")
plt.ylabel("EVs per Charging Station")
plt.tight_layout()
plt.savefig("ev_per_station_ratio.png", bbox_inches="tight")
plt.show()

"""##Visualization 7 GIS Map of EV Adoption by County"""

url = "https://www2.census.gov/geo/tiger/TIGER2025/COUNTY/tl_2025_us_county.zip"
counties = gpd.read_file(url)

md_counties = counties[counties["STATEFP"] == "24"].copy()
md_counties = md_counties[["NAME", "geometry"]]

map_df = md_counties.merge(df, left_on="NAME", right_on="County", how="inner")

plt.figure(figsize=(10, 10))
map_df.plot(column="EV_Total", legend=True)
plt.title("GIS Map of EV Adoption by County in Maryland")
plt.axis("off")
plt.tight_layout()
plt.savefig("gis_map_ev_adoption.png", bbox_inches="tight")
plt.show()

"""##Visualization 8 GIS Map of Charging Stations by County"""

plt.figure(figsize=(10, 10))
map_df.plot(column="Charging_Stations", legend=True)
plt.title("GIS Map of Charging Stations by County in Maryland")
plt.axis("off")
plt.tight_layout()
plt.savefig("gis_map_charging_stations.png", bbox_inches="tight")
plt.show()
