# -*- coding: utf-8 -*-
"""Capstone 205 Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sg6o8HoE7nsvC7kRFx8JRVtCPdt2C6lY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.api as sm
from scipy import stats

df = pd.read_csv("final_dataset.csv")

print("Dataset shape:", df.shape)
print(df[["County", "EV_Total", "Charging_Stations",
          "Stations_With_Level2", "Stations_With_DC_Fast"]].to_string())

y  = df["EV_Total"]                         # dependent variable
X1 = df[["Charging_Stations"]]              # Model 1 predictor
X2 = df[["Stations_With_DC_Fast",
          "Stations_With_Level2"]]          # Model 2 predictors

# ── 3. MODEL 1 — Simple Linear Regression ────────────────────
#       EV Registrations ~ Total Charging Stations

print("\n" + "="*60)
print("MODEL 1: EV Registrations ~ Total Charging Stations")
print("="*60)

model1 = LinearRegression()
model1.fit(X1, y)
y_pred1 = model1.predict(X1)

r2_1   = r2_score(y, y_pred1)
rmse_1 = np.sqrt(mean_squared_error(y, y_pred1))
slope1 = model1.coef_[0]
intercept1 = model1.intercept_

print(f"  Intercept        : {intercept1:,.2f}")
print(f"  Slope            : {slope1:,.4f}  EVs per charging station")
print(f"  R²               : {r2_1:.4f}")
print(f"  RMSE             : {rmse_1:,.2f} EVs")

# Pearson r and p-value
r_val, p_val = stats.pearsonr(df["Charging_Stations"], y)
print(f"  Pearson r        : {r_val:.4f}")
print(f"  p-value          : {p_val:.6f}")

# Full OLS summary with confidence intervals
X1_sm = sm.add_constant(X1)
ols1  = sm.OLS(y, X1_sm).fit()
print("\n--- OLS Summary (Model 1) ---")
print(ols1.summary())

# ── 4. MODEL 2 — Multiple Linear Regression ──────────────────
#       EV Registrations ~ DC Fast Stations + Level 2 Stations

print("\n" + "="*60)
print("MODEL 2: EV Registrations ~ DC Fast Stations + Level 2 Stations")
print("="*60)

model2 = LinearRegression()
model2.fit(X2, y)
y_pred2 = model2.predict(X2)

r2_2   = r2_score(y, y_pred2)
rmse_2 = np.sqrt(mean_squared_error(y, y_pred2))

print(f"  Intercept        : {model2.intercept_:,.2f}")
print(f"  Coef (DC Fast)   : {model2.coef_[0]:,.4f}  EVs per DC Fast station")
print(f"  Coef (Level 2)   : {model2.coef_[1]:,.4f}  EVs per Level 2 station")
print(f"  R²               : {r2_2:.4f}")
print(f"  Adjusted R²      : see OLS summary below")
print(f"  RMSE             : {rmse_2:,.2f} EVs")

X2_sm = sm.add_constant(X2)
ols2  = sm.OLS(y, X2_sm).fit()
print("\n--- OLS Summary (Model 2) ---")
print(ols2.summary())

# ── 5. Model comparison ───────────────────────────────────────
print("\n" + "="*60)
print("MODEL COMPARISON")
print("="*60)
print(f"  Model 1 R²   : {r2_1:.4f}   (simple — total stations)")
print(f"  Model 2 R²   : {r2_2:.4f}   (multiple — DC Fast + Level 2)")
print(f"  Model 1 RMSE : {rmse_1:,.0f} EVs")
print(f"  Model 2 RMSE : {rmse_2:,.0f} EVs")

# ── 6. Visualizations ─────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(14, 11))
fig.suptitle("EV Adoption vs. Charging Infrastructure — Maryland Counties (Feb 2026)",
             fontsize=14, fontweight="bold", y=1.01)

# --- 6a. Model 1: scatter + regression line ---
ax = axes[0, 0]
ax.scatter(df["Charging_Stations"], y, color="steelblue", edgecolors="white",
           s=80, zorder=3, label="County")

# Annotate notable counties
for _, row in df.iterrows():
    if row["EV_Total"] > 5000 or row["Charging_Stations"] > 100:
        ax.annotate(row["County"], (row["Charging_Stations"], row["EV_Total"]),
                    textcoords="offset points", xytext=(5, 4), fontsize=7)

x_range = np.linspace(df["Charging_Stations"].min(),
                       df["Charging_Stations"].max(), 200).reshape(-1, 1)
ax.plot(x_range, model1.predict(x_range), color="crimson",
        linewidth=2, label=f"Fit  R²={r2_1:.3f}")
ax.set_xlabel("Total Charging Stations")
ax.set_ylabel("EV Registrations")
ax.set_title("Model 1: EV ~ Total Charging Stations")
ax.legend()
ax.grid(True, alpha=0.3)

# --- 6b. Model 2: predicted vs actual ---
ax = axes[0, 1]
ax.scatter(y_pred2, y, color="darkorange", edgecolors="white", s=80, zorder=3)
ax.plot([y.min(), y.max()], [y.min(), y.max()],
        "k--", linewidth=1.5, label="Perfect fit")
ax.set_xlabel("Predicted EV Registrations")
ax.set_ylabel("Actual EV Registrations")
ax.set_title(f"Model 2: Predicted vs Actual  (R²={r2_2:.3f})")
ax.legend()
ax.grid(True, alpha=0.3)

# --- 6c. EV per Station by county (infrastructure gap) ---
ax = axes[1, 0]
data_sorted = df.sort_values("EV_per_Station", ascending=True)
colors = ["crimson" if x > 60 else "steelblue" for x in data_sorted["EV_per_Station"]]
bars = ax.barh(data_sorted["County"], data_sorted["EV_per_Station"],
               color=colors, edgecolor="white")
ax.axvline(42.5, color="black", linestyle="--", linewidth=1.2,
           label=f"State avg ≈ 42.5")
ax.set_xlabel("EVs per Charging Station")
ax.set_title("Infrastructure Gap: EVs per Charging Station\n(red = high demand pressure)")
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3, axis="x")

# --- 6d. DC Fast vs Level 2 scatter, size=EV_Total ---
ax = axes[1, 1]
scatter = ax.scatter(df["Stations_With_DC_Fast"], df["Stations_With_Level2"],
                     c=df["EV_Total"], cmap="YlOrRd",
                     s=df["EV_Total"] / 40 + 30, edgecolors="gray",
                     linewidths=0.5, zorder=3)
plt.colorbar(scatter, ax=ax, label="EV Registrations")
ax.set_xlabel("Stations with DC Fast Chargers")
ax.set_ylabel("Stations with Level 2 Chargers")
ax.set_title("Charger Mix by County\n(dot size & color = EV registrations)")
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("ev_charging_regression.png", dpi=150, bbox_inches="tight")
plt.show()
print("Plot saved as ev_charging_regression.png")

import matplotlib.pyplot as plt
import numpy as np

# Make sure your dataframe has counties in the SAME order as your model input
# Example:
counties = df["County"].values  # adjust if your df name is different

# Get unique counties
unique_counties = np.unique(counties)

# Create a color map (enough distinct colors)
cmap = plt.cm.get_cmap('tab20', len(unique_counties))

# Map each county → color
county_color_map = {county: cmap(i) for i, county in enumerate(unique_counties)}

# ── 7. Residual diagnostics ───────────────────────────────────
fig2, axes2 = plt.subplots(1, 2, figsize=(14, 5))
fig2.suptitle("Residual Diagnostics", fontsize=13, fontweight="bold")

for i, (resid, label) in enumerate([
        (ols1.resid, "Model 1 — Total Stations"),
        (ols2.resid, "Model 2 — DC Fast + Level 2")]):

    ax = axes2[i]

    for j in range(len(resid)):
        county = counties[j]
        ax.scatter(j, resid[j],
                   color=county_color_map[county],
                   edgecolors="white", s=70)

    ax.axhline(0, color="black", linestyle="--", linewidth=1)
    ax.set_xlabel("Observation index")
    ax.set_ylabel("Residual (actual − predicted)")
    ax.set_title(label)
    ax.grid(True, alpha=0.3)

# Create legend (outside plot so it doesn't clutter)
handles = [
    plt.Line2D([0], [0], marker='o', color='w',
               markerfacecolor=county_color_map[county],
               markersize=8, label=county)
    for county in unique_counties
]

fig2.legend(handles=handles, title="County",
            bbox_to_anchor=(1.05, 0.5), loc="center left")

plt.tight_layout()
plt.savefig("ev_charging_residuals_colored.png", dpi=150, bbox_inches="tight")
plt.show()

print("Residual plot saved as ev_charging_residuals_colored.png")

"""##Model 1
Total charging stations explain about 75% of the variation in EV registrations across Maryland counties. The relationship is highly significant (p < 0.0001). For every additional charging station in a county, roughly 62 more EVs are registered there. The strong correlation (r = 0.867) tells you the two are moving together. It could be that EV adoption drives demand for stations, or that station availability attracts EV buyers

##Model 2

Splitting charger types explains 82% of EV registration variance — a meaningful improvement over Model 1. The RMSE also drops by ~600 EVs, so predictions are more accurate.

The Level 2 coefficient is strongly positive and significant: counties with more Level 2 stations are associated with far more EV registrations. Level 2 chargers are the everyday workhorse — used at home, workplaces, and shopping centers for overnight or multi-hour charging. Their presence reflects mature, accessible infrastructure.

The DC Fast coefficient is negative (−245) and statistically significant. This is counterintuitive at first, but it makes real-world sense: DC Fast chargers are concentrated in highway corridors and commercial clusters — places optimized for passing-through drivers, not necessarily where large EV populations live. Counties like Garrett, Dorchester, and Kent have DC Fast chargers but very few registered EVs, because those stations serve travelers rather than residents. The negative sign is a suppressor effect — once you control for Level 2 coverage, DC Fast stations are inversely associated with residential EV density.

#Is Infrastructure Keeping Pace?

The short answer: no, and unevenly so.
The EV_per_Station column reveals the gap directly. The statewide average is 42.5 EVs sharing every charging station, but high-demand counties are far worse:

Montgomery County: 97.7 EVs per station — nearly 2× the state average, with 34,767 EVs and 356 stations

Frederick: 85.3 EVs/station

Carroll: 84.1 EVs/station

Howard: 78.3 EVs/station

Meanwhile rural counties like Garrett (6.5), Kent (10.9), and Dorchester (10.9) are over-served relative to their EV populations — but those are often highway DC Fast chargers, not the residential infrastructure that drives adoption.

The infrastructure gap is concentrated in suburban/high-growth counties where EVs are growing fastest but Level 2 station deployment hasn't matched pace. The models together confirm that Level 2 expansion — not just DC Fast — is the policy lever most associated with higher EV adoption.
"""