# -*- coding: utf-8 -*-
"""Capstone 205 Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sg6o8HoE7nsvC7kRFx8JRVtCPdt2C6lY
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# ── LOAD DATA ─────────────────────────────────────────────────
df      = pd.read_csv("final_dataset.csv")
inc_raw = pd.read_csv("maryland_income_by_county.csv")

# ── CLEAN & MERGE INCOME ──────────────────────────────────────
inc = inc_raw[~inc_raw['County'].isin(['United States', 'Maryland', 'Baltimore City'])].copy()
inc['County'] = inc['County'].str.replace(' County', '').str.strip()

name_map = {
    'Allegany': 'Allegany', 'Anne Arundel': 'Anne Arundel',
    'Baltimore': 'Baltimore County', 'Calvert': 'Calvert',
    'Caroline': 'Caroline', 'Carroll': 'Carroll', 'Cecil': 'Cecil',
    'Charles': 'Charles', 'Dorchester': 'Dorchester', 'Frederick': 'Frederick',
    'Garrett': 'Garrett', 'Harford': 'Harford', 'Howard': 'Howard',
    'Kent': 'Kent', 'Montgomery': 'Montgomery',
    'Prince Georges': "Prince George's", 'Queen Annes': "Queen Anne's",
    'Somerset': 'Somerset', 'St. Marys': "St. Mary's", 'Talbot': 'Talbot',
    'Washington': 'Washington', 'Wicomico': 'Wicomico', 'Worcester': 'Worcester',
}
inc['County'] = inc['County'].map(name_map)
inc = inc.dropna(subset=['County'])
inc = inc.rename(columns={'Value (Dollars)': 'Median_Income'})[['County', 'Median_Income']]

data = df.merge(inc, on='County', how='inner')
print(f"Dataset ready: {data.shape[0]} counties\n")

#  MODEL 1 — Simple Linear Regression
print("=" * 55)
print("MODEL 1: EV_Total ~ Charging_Stations")
print("=" * 55)

X1 = sm.add_constant(data[['Charging_Stations']])
m1 = sm.OLS(data['EV_Total'], X1).fit()

r1, p1 = stats.pearsonr(data['Charging_Stations'], data['EV_Total'])

print(f"R²             : {m1.rsquared:.3f}")
print(f"Adjusted R²    : {m1.rsquared_adj:.3f}")
print(f"Slope          : +{m1.params['Charging_Stations']:.1f} EVs per station")
print(f"Pearson r      : {r1:.3f}")
print(f"p-value        : {m1.pvalues['Charging_Stations']:.4f}")
print(f"RMSE           : {np.sqrt(m1.mse_resid):,.0f} EVs")
print()
print(m1.summary())

#  MODEL 2 — Multiple Linear Regression
print("\n" + "=" * 55)
print("MODEL 2: EV_Total ~ Level2 Stations + DC Fast Stations")
print("=" * 55)

X2 = sm.add_constant(data[['Stations_With_Level2', 'Stations_With_DC_Fast']])
m2 = sm.OLS(data['EV_Total'], X2).fit()

print(f"R²                    : {m2.rsquared:.3f}")
print(f"Adjusted R²           : {m2.rsquared_adj:.3f}")
print(f"β (Level 2 Stations)  : +{m2.params['Stations_With_Level2']:.1f}")
print(f"β (DC Fast Stations)  : +{m2.params['Stations_With_DC_Fast']:.1f}")
print(f"p (Level 2)           : {m2.pvalues['Stations_With_Level2']:.4f}")
print(f"p (DC Fast)           : {m2.pvalues['Stations_With_DC_Fast']:.4f}")
print(f"RMSE                  : {np.sqrt(m2.mse_resid):,.0f} EVs")
print()
print(m2.summary())

#  MODEL 3 — Multiple Linear Regression with Income
print("\n" + "=" * 55)
print("MODEL 3: EV_Total ~ Charging_Stations + Median_Income")
print("=" * 55)

X3 = sm.add_constant(data[['Charging_Stations', 'Median_Income']])
m3 = sm.OLS(data['EV_Total'], X3).fit()

print(f"R²                      : {m3.rsquared:.3f}")
print(f"Adjusted R²             : {m3.rsquared_adj:.3f}")
print(f"β (Charging Stations)   : +{m3.params['Charging_Stations']:.1f}")
print(f"β (Median Income)       : +{m3.params['Median_Income']:.4f}")
print(f"p (Charging Stations)   : {m3.pvalues['Charging_Stations']:.4f}")
print(f"p (Median Income)       : {m3.pvalues['Median_Income']:.4f}")
print(f"RMSE                    : {np.sqrt(m3.mse_resid):,.0f} EVs")
print(f"\nR² improvement over Model 1: +{m3.rsquared - m1.rsquared:.3f}")
print()
print(m3.summary())

#  SUMMARY
print("\n" + "=" * 55)
print("MODEL COMPARISON SUMMARY")
print("=" * 55)
print(f"{'Model':<40} {'R²':>6}  {'Adj R²':>8}")
print("-" * 55)
print(f"{'Model 1 — Charging Stations only':<40} {m1.rsquared:>6.3f}  {m1.rsquared_adj:>8.3f}")
print(f"{'Model 2 — Level 2 + DC Fast':<40} {m2.rsquared:>6.3f}  {m2.rsquared_adj:>8.3f}")
print(f"{'Model 3 — Stations + Income':<40} {m3.rsquared:>6.3f}  {m3.rsquared_adj:>8.3f}")