# -*- coding: utf-8 -*-
"""Capstone 205 Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sg6o8HoE7nsvC7kRFx8JRVtCPdt2C6lY
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
import warnings
warnings.filterwarnings('ignore')


df = pd.read_csv("final_dataset.csv")

# Income
inc_raw = pd.read_csv("maryland_income_by_county.csv")
inc = inc_raw[~inc_raw['County'].isin(['United States', 'Maryland', 'Baltimore City'])].copy()
inc['County'] = inc['County'].str.replace(' County', '').str.strip()

name_map = {
    'Allegany': 'Allegany', 'Anne Arundel': 'Anne Arundel',
    'Baltimore': 'Baltimore County', 'Calvert': 'Calvert',
    'Caroline': 'Caroline', 'Carroll': 'Carroll', 'Cecil': 'Cecil',
    'Charles': 'Charles', 'Dorchester': 'Dorchester', 'Frederick': 'Frederick',
    'Garrett': 'Garrett', 'Harford': 'Harford', 'Howard': 'Howard',
    'Kent': 'Kent', 'Montgomery': 'Montgomery',
    "Prince George's": "Prince George's", 'Prince Georges': "Prince George's",
    "Queen Anne's": "Queen Anne's",       'Queen Annes':   "Queen Anne's",
    "St. Mary's": "St. Mary's",           'St. Marys':     "St. Mary's",
    'Somerset': 'Somerset', 'Talbot': 'Talbot', 'Washington': 'Washington',
    'Wicomico': 'Wicomico', 'Worcester': 'Worcester',
}
inc['County'] = inc['County'].map(name_map)
inc = inc.dropna(subset=['County'])
inc = inc.rename(columns={'Value (Dollars)': 'Median_Income'})[['County', 'Median_Income']]

# Population
pop_raw = pd.read_csv("maryland_population.csv", skiprows=8)
pop_raw.columns = ['Geographic Area Name', 'Population Estimate']
pop_raw = pop_raw[pop_raw['Geographic Area Name'].str.contains('County', na=False)].copy()
pop_raw['County'] = (
    pop_raw['Geographic Area Name']
    .str.replace(', Maryland', '', regex=False)
    .str.replace(' County', '', regex=False)
    .str.strip()
)
pop_raw['County'] = pop_raw['County'].map(name_map)
pop_raw['Population'] = (
    pop_raw['Population Estimate']
    .astype(str).str.replace(',', '', regex=False)
    .astype(float)
)
pop = pop_raw.dropna(subset=['County'])[['County', 'Population']]

# Merge
data = df.merge(inc, on='County', how='inner')
data = data.merge(pop, on='County', how='inner')

data['EV_per_Capita']     = data['EV_Total'] / data['Population']
data['Stations_per_1000'] = data['Charging_Stations'] / data['Population'] * 1000

print(f"Dataset: {data.shape[0]} counties\n")
print(data[['County', 'EV_per_Capita', 'Stations_per_1000', 'Median_Income']].to_string(index=False))


# Model

X = sm.add_constant(data[['Stations_per_1000', 'Median_Income']])
y = data['EV_per_Capita']

model = sm.OLS(y, X).fit()

print("\n" + "=" * 60)
print("MODEL: EV_per_Capita ~ Stations_per_1000 + Median_Income")
print("=" * 60)
print(model.summary())



# Summary
sep   = "=" * 60
label = "MODEL: EV_per_Capita ~ Stations_per_1000 + Median_Income"
rmse  = np.sqrt(model.mse_resid)

print(f"\n{sep}")
print(label)
print(sep)
print(f"R²                      : {model.rsquared:.3f}")
print(f"Adjusted R²             : {model.rsquared_adj:.3f}")
print(f"β (Stations_per_1000)   : {model.params['Stations_per_1000']:+.6f}")
print(f"β (Median Income)       : {model.params['Median_Income']:+.2e}")
print(f"p (Stations_per_1000)   : {model.pvalues['Stations_per_1000']:.4f}")
print(f"p (Median Income)       : {model.pvalues['Median_Income']:.4f}")
print(f"RMSE                    : {rmse:.6f} EVs per capita")
print(sep)

"""# Assumption 1: Linearity"""

import matplotlib.pyplot as plt

fitted = model.fittedvalues
residuals = model.resid

plt.figure(figsize=(8, 5))
plt.scatter(fitted, residuals)
plt.axhline(0, linestyle='--')
plt.xlabel("Fitted Values")
plt.ylabel("Residuals")
plt.title("Residuals vs Fitted Values: EV_per_Capita Model")
plt.show()

"""# Assumtion 2: Normality of residuals"""

import statsmodels.api as sm
import matplotlib.pyplot as plt

standardized_residuals = model.get_influence().resid_studentized_internal

sm.qqplot(standardized_residuals, line='45')
plt.title("Q-Q Plot of Standardized Residuals")
plt.show()

"""# Assumption 3 Multicollinearity Check: VIF"""

vif_data = pd.DataFrame()
vif_data["Variable"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

print("VIF Results:")
print(vif_data)

"""# Assumption 4 Equal Variance Check: Breusch-Pagan Test"""

bp_test = het_breuschpagan(model.resid, model.model.exog)

bp_results = pd.DataFrame({
    "Test": ["Lagrange Multiplier Statistic", "LM p-value", "F Statistic", "F p-value"],
    "Value": bp_test
})

print("Breusch-Pagan Test Results:")
print(bp_results)

"""# Assumtion 5 Independence Check: Durbin-Watson Test"""

dw_stat = durbin_watson(model.resid)

print("Durbin-Watson Statistic:", dw_stat)